version: "3.8"

services:
  rabbit:
    image: rabbitmq:3-management       # 버전 명시 권장 (예: 3.13-management)
    container_name: rabbitmq-1
    networks:
      - common                          # 이미 존재하는 공용 네트워크 사용
    ports:
      - "5672:5672"     # AMQP (Spring ↔ RabbitMQ)
      - "61613:61613"   # STOMP (Relay가 여기에 붙음)
      - "15672:15672"   # Management UI (로컬에서만)
    environment:
      TZ: Asia/Seoul                    # 타임존 설정
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: "$PASSWORD_1"
    volumes:
      - ./volumes/etc/rabbitmq:/etc/rabbitmq
      - ./volumes/var/lib/rabbitmq:/var/lib/rabbitmq
      - ./volumes/var/log/rabbitmq:/var/log/rabbitmq
    command: >
      sh -c "
        rabbitmq-plugins enable rabbitmq_management &&
        rabbitmq-plugins enable rabbitmq_stomp &&
        rabbitmq-server
      "
networks:
  common:
    external: true                      # 이미 만들어진 네트워크를 사용