version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_1
    restart: unless-stopped
    networks:
      - common
    ports:
      - "5672:5672"
      - "61613:61613"
      - "15672:15672"
    environment:
      TZ: Asia/Seoul
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${PASSWORD_1}
    volumes:
      - /dockerProjects/rabbitmq_1/volumes/etc/rabbitmq:/etc/rabbitmq
      - /dockerProjects/rabbitmq_1/volumes/var/lib/rabbitmq:/var/lib/rabbitmq
      - /dockerProjects/rabbitmq_1/volumes/var/log/rabbitmq:/var/log/rabbitmq
    command: >
      sh -c "
        rabbitmq-plugins enable rabbitmq_management &&
        rabbitmq-plugins enable rabbitmq_stomp &&
        rabbitmq-server
      "

networks:
  common:
    external: true
